### ISSUE TITLE
下载了你的代码，login接口报错

### ISSUE THREAD

**Issue by hexuebing** [cloudfreexiao/RillAdmin#1]
`2019/02/25 18:51:03 [error] 12550#2105990: *3 [lua] session.lua:54: mw_session(): session_aes_key and session_aes_secret should be set for session middleware, client: 127.0.0.1, server: , request: "OPTIONS /api/login HTTP/1.1", host: "localhost:7777", referrer: "http://localhost:10000/"
2019/02/25 18:51:03 [error] 12550#2105990: *3 [lua] log_api.lua:23: ERROR(): [31m[error]error: Oh! no handler to process method: options
[0m, client: 127.0.0.1, server: , request: "OPTIONS /api/login HTTP/1.1", host: "localhost:7777", referrer: "http://localhost:10000/"
2019/02/25 18:51:03 [error] 12550#2105990: *4 [lua] session.lua:54: mw_session(): session_aes_key and session_aes_secret should be set for session middleware, client: 127.0.0.1, server: , request: "POST /api/login HTTP/1.1", host: "localhost:7777", referrer: "http://localhost:10000/"
2019/02/25 18:51:03 [error] 12550#2105990: *4 [lua] log_api.lua:23: ERROR(): [31m[error]error: session_aes_key and session_aes_secret should be set for session middleware
[0m, client: 127.0.0.1, server: , request: "POST /api/login HTTP/1.1", host: "localhost:7777", referrer: "http://localhost:10000/"`
我实在是不懂为什么？所以还请大神指点

**Comment by cloudfreexiao** [comment]
看日志像 是 你配置了本机ip？ 我记得 cors 不能配置 本机ip 你对应修改成 静态ip试试
https://github.com/cloudfreexiao/RillAdmin/blob/master/frontend/config/dev.env.js#L7
https://github.com/cloudfreexiao/RillAdmin/blob/master/frontend/config/prod.env.js#L4
https://github.com/cloudfreexiao/RillAdmin/blob/master/backend-or/app/config/config.lua#L59

**Comment by cloudfreexiao** [comment]
@hexb0307  我刚修改了下 openresty 的工程 你再试试
新增了一个 nginx 静态资源服务

**Comment by hexuebing** [comment]
非常感谢您的回复，最近忙于别的事情就没有关注这个，我重新拉一下代码试试。
